language: node_js
sudo: required
node_js:
  - 10
cache:
  yarn: true
  hexo-cli: true
  directories:
    - node_modules

before_install:
  - git config --global user.name "lsl233"
  - git config --global user.name "ahands233@gmail.com"
  - sed -i'' "s~repo-url~https://${GITHUB_TOKEN}@github.com/lsl233/new-blog.git~" _config.yml 
  - npm install -g hexo-cli

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_success:
  - hexo d